// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vctehuhjqgunkaeujnkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjdGVodWhqcWd1bmthZXVqbmtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NjgzNTYsImV4cCI6MjA3MDI0NDM1Nn0.0SrBLVMFvRNL38iI93vzJhbUxy2R5TmQnZMY9aoGuBc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});